export const columns = [
  {
    title: 'ID',
    dataIndex: 'id',
    width: '50px',
  },
  {
    title: '利润中心',
    dataIndex: 'profitCenterName',
    width: '200px',
  },
  {
    title: '项目名称',
    dataIndex: 'projectName',
    width: '150px',
  },
  {
    title: '项目分期名称',
    dataIndex: 'stagesName',
    width: '200px',
  },
  {
    title: '房间编码',
    dataIndex: 'roomCode',
    width: '150px',
  },
  {
    title: '房间交付日期',
    dataIndex: 'deliveryDate',
    width: '100px',
  },
  {
    title: '成交金额',
    dataIndex: 'dealPrice',
    width: '100px',
  },
  {
    title: '税率',
    dataIndex: 'taxRate',
    width: '100px',
  },
  {
    title: '楼栋名称',
    dataIndex: 'buildingName',
    width: '300px',
  },
];

export const dataSource = [
  {
    id: '1',
    profitCenterName: '香格里拉利润中心2',
    projectName: '香格里拉碧桂园44',
    stagesName: '香格里拉凤凰碧桂园01（二期）',
    roomCode: 'XGLL1001-501',
    deliveryDate: '2018-07-02',
    dealPrice: '500.00',
    taxRate: '10%',
    buildingName: '香格里拉凤凰碧桂园10号楼5单501',
  },
  {
    id: '2',
    profitCenterName: '香格里拉利润中心2',
    projectName: '香格里拉碧桂园44',
    stagesName: '香格里拉凤凰碧桂园02（二期）',
    roomCode: 'XGLL1001-401',
    deliveryDate: '2018-07-01',
    dealPrice: '200.00',
    taxRate: '11%',
    buildingName: '香格里拉凤凰碧桂园10号楼5单元701',
  },
  {
    id: '3',
    profitCenterName: '香格里拉利润中心2',
    projectName: '香格里拉碧桂园44',
    stagesName: '香格里拉凤凰碧桂园02（二期）',
    roomCode: 'XGLL1001-401',
    deliveryDate: '2018-07-01',
    dealPrice: '200.00',
    taxRate: '11%',
    buildingName: '香格里拉凤凰碧桂园10号楼5单元701',
  },
  {
    id: '4',
    profitCenterName: '香格里拉利润中心2',
    projectName: '香格里拉碧桂园44',
    stagesName: '香格里拉凤凰碧桂园02（二期）',
    roomCode: 'XGLL1001-401',
    deliveryDate: '2018-07-01',
    dealPrice: '200.00',
    taxRate: '11%',
    buildingName: '香格里拉凤凰碧桂园10号楼5单元701',
  },
  {
    id: '5',
    profitCenterName: '香格里拉利润中心2',
    projectName: '香格里拉碧桂园44',
    stagesName: '香格里拉凤凰碧桂园02（二期）',
    roomCode: 'XGLL1001-401',
    deliveryDate: '2018-07-01',
    dealPrice: '200.00',
    taxRate: '11%',
    buildingName: '香格里拉凤凰碧桂园10号楼5单元701',
  },
];
